"""add notification_sent into task

Revision ID: 7ebed770b45c
Revises: 7f2e7988a31b
Create Date: 2026-04-03 17:00:36.118137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ebed770b45c'
down_revision: Union[str, Sequence[str], None] = '7f2e7988a31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    op.alter_column('tasks', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('tasks', 'notification_sent')
    # ### end Alembic commands ###
