"""add creation date into task

Revision ID: 7f2e7988a31b
Revises: 2026bd30ee71
Create Date: 2026-04-02 13:45:30.413407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2e7988a31b'
down_revision: Union[str, Sequence[str], None] = '2026bd30ee71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('tasks', 'creation_date')
    # ### end Alembic commands ###
